### ISSUE TITLE
Language improvements

### ISSUE THREAD

**Issue by AlexShevyakov** [contributorpw/google-apps-script-snippets-hugo-site#6]
**Original: When I was learning I missed such samples. I really hope it will be useful for you too.**
_Suggested: I wish I could have samples like these when I was learning to code._

**Original: These snippets are focused on simple and common use. Very often (in Google Apps Script) we need to copy and paste some code into our project for everything to work. These snippets are for this.**
_Suggested: These simple and common-case snippets can be re-used within a GAS project._

**Original: You just copy the files to your project.**
_Suggested: Just copy the files to your project._

**Original: Almost every snippet is provided with a main code file and a manifest.** 
_Suggested: Almost every snippet is provided with the main code file and a manifest._ 

**Original: Stay attentive.**
_Suggested: --to be remoived--_

**Original: When you take a snippet, you get two manifests: yours one in the current project and a snippet manifest.**
_Suggested: When you take a snippet, you get two manifests: yours in the current project and the snippet manifest._

**Original: Do know something cool about Google Apps Script? Leave an issue or PR**
_Suggested: Do **you** know something cool about Google Apps Script? Leave an issue or PR_

**Comment by contributorpw** [comment]
Thank you so much!
